// Top-level build file where you can add configuration options common to all sub-projects/modules.
//file:noinspection GroovyAssignabilityCheck
//file:noinspection GrUnresolvedAccess
buildscript {
    ext {
        // last version is here [https://play.google.com/console/u/0/developers/6867856033872987263/app/4972072127034375090/releases/overview]
        version_code = 28
        version_name = "2.2.8"

        // sdk versions
        compile_sdk_version = 37
        skd_preview = "Baklava"
        build_tools_version = "36.0.0"
        min_sdk_version = 23
        target_sdk_version = 36

        applicationId = "io.github.turskyi.travellingpro"
    }
    dependencies {
    }
}

plugins {
    alias(libs.plugins.android.application) apply false
    alias(libs.plugins.android.library) apply false
    alias(libs.plugins.jetbrains.kotlin.android) apply false
    alias(libs.plugins.google.gms.google.services) apply false
    alias(libs.plugins.google.firebase.crashlytics) apply false
    alias(libs.plugins.google.firebase.firebase.perf) apply false
}

subprojects {
    afterEvaluate {
        dependencies {
            // (Asynchronous programming) coroutines
            implementation libs.kotlinx.coroutines.core

            // Retrofit2
            implementation libs.retrofit
            implementation libs.converter.gson
        }
        if (project.extensions.findByName("android") != null) {
            dependencies {
                implementation libs.kotlinx.coroutines.android

                // Tried to upgrade to 3.3.6 and all versions between - does not compile.
                implementation libs.paging.runtime

                /* Bill of Materials for the Firebase platform.
                 * When using the BoM, no need to specify versions in Firebase library dependencies */
                implementation platform(libs.firebase.bom)

                // Declaring the dependencies for the Crashlytics library
                implementation libs.firebase.crashlytics.ktx

                // Firebase SDK for Google Analytics library
                implementation libs.firebase.analytics.ktx

                // Declaring the dependency for the Cloud Firestore library
                implementation libs.firebase.firestore.ktx
//            object storage service
                implementation libs.firebase.storage.ktx

                // authentication (to get current user etc.)
                implementation libs.firebase.auth.ktx

                // avoids "Service not registered" exception
                implementation libs.play.services.basement
            }
        }
    }
}

allprojects {
}

ext {
    getParam = { key ->
        def value = System.getenv(key) ?: project.findProperty("env.$key")
        if (value) {
            println "$key = $value"
        }
        return value
    }
    HOST_URL = getParam("HOST_URL")

    SIGNING_KEY_DEBUG_PATH = getParam("SIGNING_KEY_DEBUG_PATH")
    SIGNING_KEY_DEBUG_PASSWORD = getParam("SIGNING_KEY_DEBUG_PASSWORD")
    SIGNING_KEY_DEBUG_KEY = getParam("SIGNING_KEY_DEBUG_KEY")
    SIGNING_KEY_DEBUG_KEY_PASSWORD = getParam("SIGNING_KEY_DEBUG_KEY_PASSWORD")

    SIGNING_KEY_RELEASE_PATH = getParam("SIGNING_KEY_RELEASE_PATH")
    SIGNING_KEY_RELEASE_PASSWORD = getParam("SIGNING_KEY_RELEASE_PASSWORD")
    SIGNING_KEY_RELEASE_KEY = getParam("SIGNING_KEY_RELEASE_KEY")
    SIGNING_KEY_RELEASE_KEY_PASSWORD = getParam("SIGNING_KEY_RELEASE_KEY_PASSWORD")
}

tasks.register('clean') {
    //noinspection GrDeprecatedAPIUsage
    delete rootProject.buildDir
}