name: Build & upload to Firebase App Distribution

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    name: Build Travelling Pro Android mobile app
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK environment (JDK 17)
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin' # Eclipse Temurin https://adoptium.net/
      - name: Generate Release APK
        run: ./gradlew assembleRelease
      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_ANDROID_APPID }}
          serviceCredentialsFileContent: ${( secrets.CREDENTIAL_FILE_CONTENT }}
          groups: testers
          releaseNotes: "Travelling Pro App Build"
          file: presentation/build/outputs/apk/release/presentation-release.apk